// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_portfolio.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createPortfolio = `-- name: CreatePortfolio :exec

INSERT INTO portfolios (id, created_at, updated_at, name, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
`

type CreatePortfolioParams struct {
	Name   string
	UserID uuid.UUID
}

func (q *Queries) CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) error {
	_, err := q.db.ExecContext(ctx, createPortfolio, arg.Name, arg.UserID)
	return err
}
