// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_transaction.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :exec

INSERT INTO transactions (id, date, stock_name, ticker, shares, price_per_share, portfolio_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateTransactionParams struct {
	StockName     string
	Ticker        string
	Shares        string
	PricePerShare string
	PortfolioID   uuid.UUID
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) error {
	_, err := q.db.ExecContext(ctx, createTransaction,
		arg.StockName,
		arg.Ticker,
		arg.Shares,
		arg.PricePerShare,
		arg.PortfolioID,
	)
	return err
}
