// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_holdings.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getHoldings = `-- name: GetHoldings :many
SELECT 
    p.name as portfolio_name,
    t.ticker,
    t.stock_name,
    SUM(t.shares)::TEXT as total_shares,
    AVG(t.price_per_share)::TEXT as avg_cost_per_share,
    SUM(t.shares * t.price_per_share)::TEXT as total_invested
FROM transactions t
JOIN portfolios p ON t.portfolio_id = p.id
WHERE p.user_id = $1
GROUP BY p.name, t.ticker, t.stock_name
ORDER BY p.name, t.ticker
`

type GetHoldingsRow struct {
	PortfolioName   string
	Ticker          string
	StockName       string
	TotalShares     string
	AvgCostPerShare string
	TotalInvested   string
}

func (q *Queries) GetHoldings(ctx context.Context, userID uuid.UUID) ([]GetHoldingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getHoldings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHoldingsRow
	for rows.Next() {
		var i GetHoldingsRow
		if err := rows.Scan(
			&i.PortfolioName,
			&i.Ticker,
			&i.StockName,
			&i.TotalShares,
			&i.AvgCostPerShare,
			&i.TotalInvested,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
