// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_portfolios.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getPortfoliosForUser = `-- name: GetPortfoliosForUser :many
SELECT id, name FROM portfolios WHERE user_id = $1
`

type GetPortfoliosForUserRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) GetPortfoliosForUser(ctx context.Context, userID uuid.UUID) ([]GetPortfoliosForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getPortfoliosForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPortfoliosForUserRow
	for rows.Next() {
		var i GetPortfoliosForUserRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
